[package]
name = "desktop_email_client_backend"
version = "0.1.0"
edition = "2024"
default-run = "desktop_email_client"

[[bin]]
name = "desktop_email_client"
path = "src/main.rs"

[[bin]]
name = "non_ipc_backend"
path = "src/developing/non_ipc_backend.rs"
required-features = ["non_ipc_backend"]

[dependencies]
desktop_email_client_shared = { path = "../shared" }
tauri = { version = "2.9.5", features = ["tracing"] }
tokio = { version = "1.49.0", features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
fuzzy-matcher = "0.3.7"
chrono = { workspace = true }
actix-web = { version = "4", optional = true }
actix-cors = { version = "0.7.1", optional = true }
async-trait = { workspace = true }
sqlx = { version = "0.8.6", features = [
	"macros",
	"sqlite",
	"runtime-tokio",
	"migrate",
	"chrono"
] }
dotenvy = { version = "0.15.7", optional = true }
async-imap = { version = "0.11.2", default-features = false, features = ["runtime-tokio"] }
async-native-tls = { version = "0.5.0", default-features = false, features = ["runtime-tokio"] }
thiserror = { workspace = true }
futures-util = { workspace = true }
keyring = { version = "3.6.3", features = ["sync-secret-service"] }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[features]
default = []
non_ipc_backend = ["actix-web", "actix-cors", "dotenvy"]
