[package]
name = "desktop_email_client_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
yew-router = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-serde = { workspace = true }
tracing-subscriber = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }